---
version: "3"

services:
  validator:
    container_name: validator
    image: pera-io/pera-node:${PERA_SHA} # UPDATE HERE
    environment:
      - RUST_BACKTRACE=1
      - RUST_LOG=info,pera_core=debug,narwhal=debug,consensus=debug,jsonrpsee=error
    labels:
      org.label-schema.name: "validator"
    ports:
      - "8080:8080"
      - "8081:8081/tcp"
      - "8081:8081/udp"
      - "8082:8082/udp"
      - "8084:8084/udp"
      - "9184:9184"
    network_mode: "host"
    volumes:
      - ./validator.yaml:/opt/pera/config/validator.yaml:ro
      - ./genesis.blob:/opt/pera/config/genesis.blob:ro
      - ../genesis/key-pairs:/opt/pera/key-pairs/:ro
      - /opt/pera/db:/opt/pera/db:rw
    command:
      [
        "/opt/pera/bin/pera-node",
        "--config-path",
        "/opt/pera/config/validator.yaml",
      ]
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "5g"
